- name: install netdata
  apt:
    name: netdata

- name: copy netdata.conf
  copy:
    src: netdata.conf
    dest: /etc/netdata.conf
    backup: yes

- name: restart netdata
  service:
    name: netdata
    state: restarted
    enabled: yes