#- name: install nginx
#   apt:
#     name: nginx-full

- name: put portopen.sh with template
  template:
    src: portopen.sh.j2
    dest: /opt/portopen.sh
    mode: 775
    backup: yes

- name: put portopen.service
  copy:
    src: portopen.service
    dest: /etc/systemd/system/portopen.service
    mode: 775

# 当日に修正
- name: put modified app.service
  copy:
    src: app.service
    dest: /etc/systemd/system/app.service
    mode: 775