# - name: install mysql
#   apt:
#     name: mysql-server

- name: copy my.cnf
  copy:
    src: my.cnf
    dest: /etc/mysql/my.cnf
    backup: yes

- name: restart mysql
  service:
    name: mysql
    state: restarted
    enabled: yes

# - name: initialize
#   shell: ./init.sh
#   args:
#     chdir: /home/isucon