- name: nginxのインストール
  #- user: name=isucon groups=sudo
  - apt: name=nginx-full
  
- name: put nginx.conf with template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: yes

- name: nginxの再起動
    - service: name=nginx state=れstarted enabled=yes