---
- hosts: all
  sudo: yes
  tasks:
    - user: name=isucon groups=sudo
    - apt: name=nginx-full
    - service: name=nginx enabled=true
    - apt: name=mysql-server
    - service: name=mysql state=started enabled=true
    - apt: name=mysqldb
    # gitでアクセスできない
    - apt: name=git
    - git: repo=https://github.com/ysokjkr/isucon9.git dest=/tmp/isucon9
    - shell: cp /tmp/isucon9/nginx/nginx_sample.conf /etc/nginx/nginx.conf
      notify:
        - reload nginx
    - name: copy my.cnf
      shell: cp /tmp/isucon9/mysql/my.cnf /etc/my.cnf
      notify:
        - restart mysqld
  #   - command: rm -rf /tmp/isucon
  #     args:
  #       removes: /tmp/isucon
  #   - file: path=/tmp/isucon state=directory 
  #   - shell: rsync -a /tmp/isucon4/qualifier/sql /tmp/isucon/
  #   - shell: rsync -a /tmp/isucon4/qualifier/webapp /tmp/isucon/
  #   - shell: |
  #       cp /tmp/isucon4/qualifier/init.sh /tmp/isucon/init.sh
  #       chmod a+x /tmp/isucon/init.sh
  #   - shell: |
  #       cp /tmp/isucon4/qualifier/ami/files/env.sh /tmp/isucon/env.sh
  #       chmod a+x /tmp/isucon/env.sh
  # .bashrcや.vimrcなどを用意してここでセットできると良いかも。.gitignoreとかも用意しておく？
  #   - shell: |
  #       cp /tmp/isucon4/qualifier/ami/files/bashrc /home/isucon/.bashrc
  #       chmod a+x /home/isucon/.bashrc
  #   - command: chown -R isucon:isucon /tmp/isucon
  #   - command: rsync -avz --delete --exclude-from=/tmp/isucon4/qualifier/ami/files/rsync_exclude.txt /tmp/isucon/ /home/isucon/
  #     sudo: yes
  # DBの初期化処理などを入れる
  # post_tasks:
  #   - command: ./init.sh
  #     sudo_user: isucon
  #     args:
  #       chdir: /home/isucon
  #   - mysql_user: name=isucon password=isucon priv=*.*:ALL state=present
  handlers:
    - name: restart mysqld
      action: service name=mysql state=restarted
    - name: reload nginx
      action: service name=nginx state=restarted