---
- hosts: all
  sudo: yes
  vars:
    # ホスト名をそれぞれ入れる
    host01: "127.0.0.1"
    host02: "127.0.0.2"
    host03: "127.0.0.3"
  tasks:
    - user: name=isucon groups=sudo
    - apt: name=nginx-full
    - service: name=nginx enabled=true
    - apt: name=mysql-server
    - service: name=mysql state=started enabled=true
    # mysqlは自分でやらないほうがいいかも・・
    - apt: name=mysql-server-5.7
    - apt: name=netdata
    - name: put nginx.conf with template
      template:
        src: ./template/nginx.conf
        dest: /etc/nginx/nginx.conf
        backup: yes
        # restartどうできる？
        # notify:
        #  - restart nginx
    - name: copy my.cnf
      copy:
        src: ./template/my.cnf
        dest: /etc/my.cnf
        backup: yes
      notify:
        - restart mysqld
    - name: copy netdata.conf
      copy:
          src: ./template/netdata.conf
          dest: /etc/netdata.conf
          backup: yes
      notify:
        - restart netdata
  #   - command: rm -rf /tmp/isucon
  #     args:
  #       removes: /tmp/isucon
  #   - file: path=/tmp/isucon state=directory 
  #   - shell: rsync -a /tmp/isucon4/qualifier/sql /tmp/isucon/
  #   - shell: rsync -a /tmp/isucon4/qualifier/webapp /tmp/isucon/
  #   - shell: |
  #       cp /tmp/isucon4/qualifier/init.sh /tmp/isucon/init.sh
  #       chmod a+x /tmp/isucon/init.sh
  #   - shell: |
  #       cp /tmp/isucon4/qualifier/ami/files/env.sh /tmp/isucon/env.sh
  #       chmod a+x /tmp/isucon/env.sh
  # .bashrcや.vimrcなどを用意してここでセットできると良いかも。.gitignoreとかも用意しておく？
  #   - shell: |
  #       cp /tmp/isucon4/qualifier/ami/files/bashrc /home/isucon/.bashrc
  #       chmod a+x /home/isucon/.bashrc
  #   - command: chown -R isucon:isucon /tmp/isucon
  #   - command: rsync -avz --delete --exclude-from=/tmp/isucon4/qualifier/ami/files/rsync_exclude.txt /tmp/isucon/ /home/isucon/
  #     sudo: yes
  # DBの初期化処理などを入れる
  # post_tasks:
  #   - command: ./init.sh
  #     sudo_user: isucon
  #     args:
  #       chdir: /home/isucon
  #   - mysql_user: name=isucon password=isucon priv=*.*:ALL state=present
  handlers:
    - name: restart mysqld
      action: service name=mysql state=restarted
    - name: restart nginx
      action: service name=nginx state=restarted
    - name: restart netdata
      action: service name=netdata state=restarted