- name: deploy middlewares
  hosts: web
  roles:
    - { role: nginx, become: yes }
    - { role: mysql, become: yes }
    - { role: netdata, become: yes }
    - { role: systemd, become: yes }
    #- { role: redis, become: yes }
    - { role: slack, become: no }