---
- hosts: all
  sudo: yes
  tasks:
    - apt: name={{item}}
      with_items:
        - git
        - vim
        - dstat
        - wget
        - unzip
        - graphviz
        - ansible
        - default-jre